# Generated by Django 4.2.14 on 2024-08-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(default="B.A.", max_length=4),
        ),
        migrations.AddField(
            model_name="education",
            name="state",
            field=models.CharField(default="MD", max_length=2),
        ),
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(default="History", max_length=70),
        ),
    ]
